import { Inter } from "next/font/google";
import "./globals.scss";
import { Navbar, Footer } from "../components";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="app">
          <div className="navbarContainer">
            <Navbar />
          </div>
          <div className="wrapper">
            {children}
          </div>
          <Footer />
        </div>
      </body>
    </html>
  );
}
